'use strict';
const WORDS = [
 {id:'cat',en:'cat',ko:'고양이',emoji:'🐱',topic:'animals'},
 {id:'dog',en:'dog',ko:'강아지',emoji:'🐶',topic:'animals'},
 {id:'rabbit',en:'rabbit',ko:'토끼',emoji:'🐰',topic:'animals'},
 {id:'duck',en:'duck',ko:'오리',emoji:'🦆',topic:'animals'},
 {id:'apple',en:'apple',ko:'사과',emoji:'🍎',topic:'food'},
 {id:'banana',en:'banana',ko:'바나나',emoji:'🍌',topic:'food'},
 {id:'pear',en:'pear',ko:'배',emoji:'🍐',topic:'food'},
 {id:'blueberry',en:'blueberry',ko:'블루베리',emoji:'🫐',topic:'food'},
 {id:'red',en:'red',ko:'빨간색',emoji:'🍎',color:'red',topic:'colors'},
 {id:'yellow',en:'yellow',ko:'노란색',emoji:'🍌',color:'yellow',topic:'colors'},
 {id:'green',en:'green',ko:'초록색',emoji:'🍐',color:'green',topic:'colors'},
 {id:'blue',en:'blue',ko:'파란색',emoji:'🫐',color:'blue',topic:'colors'},
 {id:'jump',en:'jump',ko:'폴짝 뛰기',emoji:'🧍',motion:'bounce',topic:'actions'},
 {id:'clap',en:'clap',ko:'손뼉 치기',emoji:'👏',motion:'clap',topic:'actions'},
 {id:'wave',en:'wave',ko:'손 흔들기',emoji:'👋',motion:'wave',topic:'actions'}
];
const BY_ID = Object.fromEntries(WORDS.map(w=>[w.id,w]));
const STICKERS = ['🐻','🌼','🦋','🍓','🌈','🌳'];
const GAMES = {
 animals:{label:'친구를 찾아요',chapter:'동물 친구',emoji:'🐻',className:'animals',topics:['animals'],instruction:'영어 소리를 듣고, 같은 친구를 찾아봐!'},
 picnic:{label:'간식을 골라요',chapter:'냠냠 소풍',emoji:'🐻',className:'food',topics:['food','colors'],instruction:'영어 소리를 듣고, 곰에게 간식을 골라 줘!'},
 actions:{label:'같이 움직여요',chapter:'몸으로 놀이',emoji:'🐻',className:'action',topics:['actions'],instruction:'영어 소리를 듣고, 같은 동작을 골라봐! 함께 해도 좋아!'},
 review:{label:'한 번 더 만나요',chapter:'다시 만나기',emoji:'🐻',className:'animals',topics:[],instruction:'우리 다시 만나볼까? 영어 소리를 듣고 그림을 골라봐!'}
};
const KEY='hello-forest-v1';
const defaults={sound:true,reducedMotion:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches||false,level:1,topic:'all',enVoice:'',koVoice:''};
let storageOK=true;
function loadSaved(){try{let saved=JSON.parse(localStorage.getItem(KEY)||'null');if(!saved||typeof saved!=='object')return {settings:{...defaults},stickers:[],missed:[]};return {settings:{...defaults,...Object.fromEntries(Object.entries(saved.settings||{}).filter(([k,v])=>k in defaults&&typeof v===typeof defaults[k])),level:[1,2,3].includes(saved.settings?.level)?saved.settings.level:1,topic:['all','food','colors'].includes(saved.settings?.topic)?saved.settings.topic:'all'},stickers:Array.isArray(saved.stickers)?[...new Set(saved.stickers.filter(x=>Number.isInteger(x)&&x>=0&&x<6))]:[],missed:Array.isArray(saved.missed)?[...new Set(saved.missed.filter(x=>BY_ID[x]))]:[]};}catch(e){storageOK=false;return {settings:{...defaults},stickers:[],missed:[]};}}
let saved=loadSaved();let settings=saved.settings;let screen='home';let session=null;let lastSticker=0;let voices=[];let audioState='idle';let audioError='';let speakGeneration=0;let speechRefs=[];let audioTimer=null;let audioUnlocked=false;
const synth='speechSynthesis' in window?window.speechSynthesis:null;
const app=document.getElementById('app');
function persist(){try{localStorage.setItem(KEY,JSON.stringify({settings,stickers:saved.stickers,missed:saved.missed}));storageOK=true;}catch(e){storageOK=false;}applyMotion();}
function applyMotion(){document.documentElement.classList.toggle('reduced-motion',settings.reducedMotion);}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function sampleWords(pool,n){let out=[];while(out.length<n){let cycle=shuffle(pool);if(out.length&&cycle[0]?.id===out[out.length-1].id&&cycle.length>1)[cycle[0],cycle[1]]=[cycle[1],cycle[0]];out.push(...cycle);}return out.slice(0,n);}
function symbol(w,animate=true){if(w.color)return `<span class="color-object ${w.color}" aria-hidden="true">${w.emoji}</span>`;return `<span class="emoji ${animate&&w.motion?w.motion:''}" aria-hidden="true">${w.emoji}</span>`;}
function header(){return `<header class="topbar"><button class="brand" data-action="home" aria-label="영어 놀이숲, 처음으로"><span class="brand-mark" aria-hidden="true">🌱</span><span>Hello Forest<small>영어 놀이숲</small></span></button><div class="top-actions"><button class="icon-btn" data-action="sound" aria-label="${settings.sound?'소리 끄기':'소리 켜기'}" aria-pressed="${settings.sound}">${settings.sound?'🔊':'🔇'}</button><button class="icon-btn settings-btn" data-action="settings" aria-label="보호자 설정"><span aria-hidden="true">⚙</span><span class="label">보호자</span></button></div></header>`;}
function renderHome(){return `<section class="home-welcome" aria-labelledby="home-title"><img class="forest-art" src="assets/forest-bear.webp" alt="초록 숲에서 손을 흔드는 배낭 멘 곰 친구" width="1536" height="1024"><div class="welcome-copy"><div class="eyebrow">HELLO, LITTLE EXPLORER!</div><h1 id="home-title">오늘은 어디서<br>놀까?</h1><p>꾹 눌러 듣고, 그림을 콕!<br>곰 친구와 함께 출발해요.</p><button class="help-inline" data-action="welcome-audio"><span aria-hidden="true">🔊</span>곰 친구 이야기 듣기</button></div></section><div class="section-top"><h2>하고 싶은 놀이를 골라요</h2><span class="quiet-note">여섯 번 만나면, 잠깐 쉬어요 🌿</span></div><section class="game-grid" aria-label="영어 놀이 고르기"><button class="game-card" data-start="animals"><span class="card-top"><span>01 · 숲속 친구</span><span class="card-play" aria-hidden="true">▶</span></span><span class="card-objects" aria-hidden="true"><span>🐰</span><span>🦆</span></span><h3>친구를 찾아요</h3><p>잘 듣고, 친구를 콕!</p></button><button class="game-card food" data-start="picnic"><span class="card-top"><span>02 · 냠냠 소풍</span><span class="card-play" aria-hidden="true">▶</span></span><span class="card-objects" aria-hidden="true"><span>🍎</span><span>🍌</span></span><h3>간식을 골라요</h3><p>과일도 색깔도 냠냠</p></button><button class="game-card action" data-start="actions"><span class="card-top"><span>03 · 몸으로 놀이</span><span class="card-play" aria-hidden="true">▶</span></span><span class="card-objects" aria-hidden="true"><span>👋</span><span>👏</span></span><h3>같이 움직여요</h3><p>손 흔들고, 짝짝짝!</p></button></section><div class="home-bottom"><button class="text-btn" data-action="stickers">🌼 나의 숲 스티커 ${saved.stickers.length?`· ${saved.stickers.length}개`:''}</button><div><button class="text-btn" data-action="guide">보호자 놀이 안내</button>${saved.missed.length?`<span aria-hidden="true"> · </span><button class="text-btn" data-start="review">다시 만나기</button>`:''}</div></div>${(!synth||audioState==='error'||audioState==='unavailable')?audioBanner():''}<p class="local-note">이름도, 시험도 없이 가볍게 놀아요.<br>놀이 기록은 이 브라우저에만 보관돼요.</p>${!storageOK?'<p class="storage-warning">지금은 기록을 저장할 수 없어요. 이번 화면에서는 계속 놀 수 있어요.</p>':''}`;}
function currentRound(){return session?.rounds[session.index];}
function audioFallback(){return !settings.sound||!synth||audioState==='error'||audioState==='unavailable'||!voices.some(v=>v.lang.toLowerCase().startsWith('en'));}
function audioBanner(){if(!audioFallback())return '';let reason=!settings.sound?'소리가 꺼져 있어요.':!synth?'이 브라우저는 음성 읽기를 지원하지 않아요.':audioState==='error'?'소리가 재생되지 않았어요.':'이 기기의 영어 목소리를 아직 찾지 못했어요.';return `<div class="audio-banner" role="status"><p>${reason} 그림 힌트로 놀거나 보호자가 아래 영어를 읽어 주세요.</p> <button data-action="retry-audio">${settings.sound?'소리 다시 시도':'소리 켜기'}</button></div>`;}
function instruction(w){if(w.topic==='colors')return '색깔을 듣고, 같은 색 바구니를 콕!';if(w.topic==='actions')return '듣고, 같은 동작을 콕! 함께 해도 좋아요.';if(w.topic==='food')return '듣고, 곰 친구에게 간식을 골라 줘요.';return '듣고, 같은 친구를 콕!';}
function renderPlay(){const r=currentRound(),w=r.target,g=GAMES[session.game],level=session.level;const reveal=level===1||r.hinted||audioFallback();let feedback=r.correct?`${w.topic==='food'||w.topic==='colors'?'냠냠, 고마워!':w.topic==='actions'?'함께 하니 재미있어!':'찾았다, 반가워!'} ${w.topic==='actions'?'✨':'🌼'}`:r.wrong.length?'괜찮아! 그림 힌트를 볼까?':'천천히 골라도 좋아요';return `<div class="play-top"><button class="back-btn" data-action="home">⌂ 놀이숲</button><div class="progress" aria-label="여섯 번 중 ${session.index+1}번째">${session.rounds.map((_,i)=>`<span class="progress-dot ${i<session.index?'done':i===session.index?'current':''}" aria-hidden="true">${i<session.index?'✓':i+1}</span>`).join('')}<span class="round-count">${session.index+1} / ${session.rounds.length}</span></div></div><section class="play-stage" aria-label="영어 그림 놀이"><div class="play-heading ${g.className}"><div><div class="eyebrow">${g.chapter} · ${['','씨앗','새싹','나무'][level]} 놀이</div><h1>${w.topic==='colors'?'어떤 색이 맛있을까?':g.label}</h1></div><div class="companion" aria-hidden="true">🐻${r.correct&&(w.topic==='food'||w.topic==='colors')?`<span class="celebrate">${w.emoji}</span>`:''}</div></div><div class="play-body"><div class="prompt-row"><button class="listen-btn" data-action="listen" aria-label="영어 소리 다시 듣기"><span class="speaker" aria-hidden="true">🔊</span><span>한 번 더 듣기<small>꾹 눌러 들어요</small></span></button>${reveal?`<div class="target-preview" aria-label="그림 힌트: ${w.ko}">${symbol(w)}</div>`:''}</div><p class="prompt-help">${instruction(w)}</p><div class="choices ${r.choices.length===3?'three':''}">${r.choices.map(c=>`<button class="choice ${r.correct&&c.id===w.id?'correct':r.wrong.includes(c.id)?'wrong':r.hinted&&c.id===w.id?'hint':''}" data-answer="${c.id}" aria-label="${c.ko}${r.correct&&c.id===w.id?', 찾았어요':''}" ${r.correct||r.wrong.includes(c.id)?'disabled':''}>${symbol(c)}${r.correct&&c.id===w.id?'<span class="check-badge" aria-hidden="true">✓</span>':''}</button>`).join('')}</div><div class="feedback" aria-live="polite" aria-atomic="true"><div class="feedback-main">${feedback}</div>${r.correct?`<div class="feedback-sub"><strong lang="en">${w.en}</strong> · ${w.ko}${w.topic==='actions'?' · 일어나지 않고 따라 해도 좋아요':''}</div>`:''}</div><div class="play-controls">${r.correct?`<button class="primary" data-action="next" id="next-round">${session.index===session.rounds.length-1?'오늘의 스티커 보기':'다음 친구 만나기'}</button><button class="secondary" data-action="say-together">🔊 같이 말해 보기</button>`:`<button class="hint-btn" data-action="hint">🌱 그림 힌트</button><button class="hint-btn" data-action="instruction">🔊 놀이 방법 듣기</button>`}</div>${audioFallback()?`<div class="parent-read">보호자가 읽어 주세요: <strong lang="en">${w.en}</strong> (${w.ko})</div>`:''}<div class="audio-state" role="status">${audioState==='speaking'?'소리를 듣고 있어요…':audioState==='pending'?'소리를 준비하고 있어요…':''}</div></div></section>${audioBanner()}<p class="local-note">점수도, 시간 제한도 없어요. 쉬고 싶으면 언제든 놀이숲으로!</p>`;}
function renderFinish(){const unique=[...new Map(session.rounds.map(r=>[r.target.id,r.target])).values()];return `<section class="finish" aria-labelledby="finish-title"><div class="finish-sticker celebrate" aria-hidden="true">${STICKERS[lastSticker]}</div><div class="eyebrow">TODAY'S LITTLE ADVENTURE</div><h1 id="finish-title">오늘도 즐겁게 놀았어!</h1><p class="lead">곰 친구가 스티커를 준비했어요.<br>이제 눈도 몸도 잠깐 쉬어 볼까요?</p><div class="finish-words" aria-label="오늘 만난 영어, 누르면 다시 들을 수 있어요">${unique.map(w=>`<button class="word-chip" data-word="${w.id}" aria-label="${w.en}, ${w.ko}, 다시 듣기">${symbol(w,false)}<span lang="en">${w.en}</span></button>`).join('')}</div><div class="finish-actions"><button class="primary" data-action="home">🌿 오늘은 여기까지</button>${session.missed.length?'<button class="secondary" data-action="review-session">다시 만나기 · 선택</button>':''}</div><p class="break-note">같이 손을 흔들며 “Bye!” 하고 마쳐요.</p></section>`;}
function render(){const focus=document.activeElement;const keep=focus?.dataset?.action;app.innerHTML=`<main class="shell">${header()}${screen==='home'?renderHome():screen==='play'?renderPlay():renderFinish()}</main>`;applyMotion();if(keep&&['listen','sound','instruction','hint','retry-audio','say-together'].includes(keep))app.querySelector(`[data-action="${keep}"]`)?.focus({preventScroll:true});}
function updateAudioView(){if(screen==='play'){const status=app.querySelector('.audio-state');if(status)status.textContent=audioState==='speaking'?'소리를 듣고 있어요…':audioState==='pending'?'소리를 준비하고 있어요…':'';} }
function loadVoices(){voices=synth?.getVoices()||[];const dialog=document.getElementById('parent-dialog');if(dialog.open){for(const lang of ['en','ko']){let select=dialog.querySelector(`[data-voice="${lang}"]`);if(select)select.innerHTML=voiceOptions(lang);}}if(screen==='play'&&voices.some(v=>v.lang.toLowerCase().startsWith('en'))&&audioState==='unavailable'){audioState='idle';render();}}
function chooseVoice(lang){const preferred=settings[lang+'Voice'];return voices.find(v=>v.voiceURI===preferred&&v.lang.toLowerCase().startsWith(lang))||voices.find(v=>v.lang.toLowerCase().startsWith(lang)&&v.localService)||voices.find(v=>v.lang.toLowerCase().startsWith(lang));}
function stopAudio(){speakGeneration++;if(audioTimer)clearTimeout(audioTimer);audioTimer=null;speechRefs=[];if(synth)synth.cancel();if(audioState==='speaking'||audioState==='pending')audioState='idle';}
function speak(parts){stopAudio();if(!settings.sound){audioState='muted';if(screen==='play')render();return false;}if(!synth||!window.SpeechSynthesisUtterance){audioState='unavailable';render();return false;}loadVoices();const gen=speakGeneration;audioUnlocked=true;audioState='pending';audioError='';updateAudioView();const queue=parts.filter(p=>p.text&&(p.lang!=='ko'||!voices.length||chooseVoice('ko')));if(!queue.length){audioState='unavailable';render();return false;}let started=false;const fail=()=>{if(gen!==speakGeneration)return;stopAudio();audioState='error';audioError='음성을 재생할 수 없어요.';render();};audioTimer=setTimeout(()=>{if(!started)fail();},5500);try{queue.forEach((part,index)=>{const u=new SpeechSynthesisUtterance(part.text);u.lang=part.lang==='ko'?'ko-KR':'en-US';u.rate=part.lang==='ko'?.9:.77;u.pitch=1.04;const v=chooseVoice(part.lang);if(v)u.voice=v;u.onstart=()=>{if(gen!==speakGeneration)return;started=true;if(audioTimer)clearTimeout(audioTimer);audioState='speaking';updateAudioView();};u.onerror=e=>{if(e.error==='canceled'||e.error==='interrupted')return;fail();};u.onend=()=>{if(gen!==speakGeneration||index!==queue.length-1)return;audioState='idle';speechRefs=[];updateAudioView();};speechRefs.push(u);synth.speak(u);});return true;}catch(e){fail();return false;}}
function prompt(withInstruction=false){const r=currentRound();if(!r)return;let parts=[];if(withInstruction)parts.push({lang:'ko',text:r.target.topic==='colors'?'영어 색깔을 듣고, 같은 색 바구니를 골라 줘!':GAMES[session.game].instruction});parts.push({lang:'en',text:r.target.en});speak(parts);}
function makeRounds(targets){let lastIndex=-1,repeats=0;return targets.map(target=>{const pool=WORDS.filter(w=>w.topic===target.topic&&w.id!==target.id);const count=settings.level===3?3:2;const distractors=shuffle(pool).slice(0,count-1);let choices=shuffle([target,...distractors]);let at=choices.findIndex(w=>w.id===target.id);if(at===lastIndex)repeats++;else repeats=0;if(repeats>=2){const other=(at+1+Math.floor(Math.random()*(choices.length-1)))%choices.length;[choices[at],choices[other]]=[choices[other],choices[at]];at=other;repeats=0;}lastIndex=at;return {target,choices,correct:false,wrong:[],hinted:false};});}
function startGame(game,reviewIds=null){if(!GAMES[game])throw new Error('지원하지 않는 놀이예요.');stopAudio();let targets;if(game==='review'){const ids=reviewIds?.length?reviewIds:saved.missed;if(!ids.length)return;targets=sampleWords(ids.filter(id=>BY_ID[id]).map(id=>BY_ID[id]),6);}else if(game==='picnic'&&settings.topic==='all'){targets=[...sampleWords(WORDS.filter(w=>w.topic==='food'),3),...sampleWords(WORDS.filter(w=>w.topic==='colors'),3)];}else{let topics=GAMES[game].topics;if(game==='picnic'&&settings.topic!=='all')topics=[settings.topic];targets=sampleWords(WORDS.filter(w=>topics.includes(w.topic)),6);}session={game,level:settings.level,rounds:makeRounds(targets),index:0,missed:[],finished:false};screen='play';render();window.scrollTo(0,0);prompt(true);}
function choose(id){const r=currentRound();if(screen!=='play'||!r||r.correct||r.wrong.includes(id)||!r.choices.some(w=>w.id===id))return false;if(id===r.target.id){r.correct=true;if(!r.wrong.length&&!r.hinted)saved.missed=saved.missed.filter(x=>x!==id);persist();render();speak([{lang:'ko',text:r.target.topic==='food'||r.target.topic==='colors'?'고마워! 맛있겠다.':r.target.topic==='actions'?'좋아! 함께 해 볼까?':'찾았다! 반가워.'},{lang:'en',text:r.target.en}]);document.getElementById('next-round')?.focus({preventScroll:true});}else{r.wrong.push(id);if(!session.missed.includes(r.target.id))session.missed.push(r.target.id);if(!saved.missed.includes(r.target.id))saved.missed.push(r.target.id);r.hinted=true;persist();render();speak([{lang:'ko',text:'괜찮아. 이 그림을 함께 찾아보자.'},{lang:'en',text:r.target.en}]);}return true;}
function nextRound(){if(!currentRound()?.correct)return;if(session.index<session.rounds.length-1){session.index++;render();prompt(false);app.querySelector('[data-action="listen"]')?.focus({preventScroll:true});}else finish();}
function finish(){if(session.finished)return;stopAudio();session.finished=true;screen='finish';lastSticker=STICKERS.findIndex((_,i)=>!saved.stickers.includes(i));if(lastSticker<0)lastSticker=Math.floor(Math.random()*STICKERS.length);if(!saved.stickers.includes(lastSticker))saved.stickers.push(lastSticker);persist();render();window.scrollTo(0,0);speak([{lang:'ko',text:'오늘도 즐겁게 놀았어! 스티커 선물이야. 이제 잠깐 쉬자.'},{lang:'en',text:'Bye!'}]);}
function home(){stopAudio();screen='home';session=null;render();window.scrollTo(0,0);}
function voiceOptions(lang){const candidates=voices.filter(v=>v.lang.toLowerCase().startsWith(lang));return `<option value="">기기에 맞게 자동 선택</option>${candidates.map(v=>`<option value="${esc(v.voiceURI)}" ${settings[lang+'Voice']===v.voiceURI?'selected':''}>${esc(v.name)} (${esc(v.lang)})${v.localService?' · 기기 음성':''}</option>`).join('')}`;}
function dialogHead(title,id){return `<div class="dialog-header"><h2 id="${id}">${title}</h2><button class="icon-btn" data-close aria-label="닫기">×</button></div>`;}
function openSettings(){stopAudio();loadVoices();const d=document.getElementById('parent-dialog');d.innerHTML=`${dialogHead('보호자 설정','parent-title')}<div class="dialog-body"><div class="setting-row"><label for="sound-setting">소리 켜기<small>한국어 안내와 영어 낱말</small></label><input id="sound-setting" data-setting="sound" type="checkbox" ${settings.sound?'checked':''}></div><div class="setting-row"><label for="motion-setting">움직임 줄이기<small>동작 그림은 보호자가 함께 보여 주세요</small></label><input id="motion-setting" data-setting="reducedMotion" type="checkbox" ${settings.reducedMotion?'checked':''}></div><div class="setting-group"><h3>우리에게 맞는 놀이</h3><div class="level-picker" role="group" aria-label="난이도">${[[1,'🌱','씨앗','그림 + 두 개'],[2,'🌿','새싹','소리 + 두 개'],[3,'🌳','나무','소리 + 세 개']].map(([n,e,l,t])=>`<button data-level="${n}" class="${settings.level===n?'active':''}" aria-pressed="${settings.level===n}"><span aria-hidden="true">${e}</span>${l}<br><small>${t}</small></button>`).join('')}</div><p class="level-desc">처음엔 씨앗으로 시작해요. 단계는 자동으로 올라가지 않아요.<br>난이도와 주제 변경은 다음 놀이부터 적용돼요.</p></div><div class="setting-group"><label for="topic-setting">냠냠 소풍에서 만날 것</label><select id="topic-setting" data-setting="topic"><option value="all" ${settings.topic==='all'?'selected':''}>과일 세 번 + 색깔 세 번</option><option value="food" ${settings.topic==='food'?'selected':''}>과일만</option><option value="colors" ${settings.topic==='colors'?'selected':''}>색깔만</option></select></div><div class="setting-group"><h3>목소리 고르기</h3><div class="voice-selects"><div><label for="en-voice">영어 목소리</label><select id="en-voice" data-voice="en">${voiceOptions('en')}</select></div><div><label for="ko-voice">한국어 목소리</label><select id="ko-voice" data-voice="ko">${voiceOptions('ko')}</select></div></div><button class="soft-btn" data-action="test-voice" style="margin-top:12px">🔊 목소리 들어 보기</button><p class="settings-status" id="voice-status">${!synth?'이 브라우저에서는 음성을 지원하지 않아요.':!voices.length?'아직 기기 목소리를 불러오지 못했어요. 소리 버튼을 눌러 확인해 주세요.':`${voices.filter(v=>v.lang.toLowerCase().startsWith('en')).length?'영어 목소리가 준비됐어요.':'영어 목소리가 없어 그림 놀이와 보호자 읽기를 사용해요.'} ${voices.some(v=>v.lang.toLowerCase().startsWith('ko'))?'한국어 안내도 들을 수 있어요.':'한국어 목소리가 없으면 보호자가 안내를 읽어 주세요.'}`}</p></div><hr class="divider"><div class="parent-copy"><strong>이 기기에만 남는 작은 기록</strong><p>스티커, 다시 만날 낱말, 설정만 이 브라우저에 저장해요. 계정이나 이름을 입력하지 않고, 마이크·카메라·녹음도 사용하지 않아요. 다른 기기와 자동으로 이어지지 않아요.</p><p>영어와 한국어는 브라우저의 음성 읽기 기능을 사용해요. 기기와 브라우저마다 목소리와 지원 여부가 달라요. 가능하면 기기 음성을 자동 선택해요. 사이트는 아이의 음성이나 놀이 기록을 서버로 보내지 않아요.</p></div><button class="danger-btn" data-action="reset-ask">놀이 기록과 설정 초기화</button><div id="reset-area"></div><p class="settings-status" id="settings-status" role="status"></p></div>`;d.showModal();}
function openGuide(){stopAudio();const d=document.getElementById('help-dialog');d.innerHTML=`${dialogHead('함께 놀아요','help-title')}<div class="dialog-body"><p class="parent-copy">글자를 몰라도 괜찮아요. 처음에는 보호자가 옆에서 함께 눌러 주세요.</p><ol class="guide-steps"><li><span><strong>먼저 목소리를 확인해요.</strong><br>보호자 설정에서 “목소리 들어 보기”를 눌러 영어와 한국어가 잘 들리는지 확인해 주세요. 안 들리면 음소거를 확인하고, 다른 목소리나 브라우저를 써 보세요. 소리 없이도 그림 힌트로 놀 수 있어요.</span></li><li><span><strong>처음에는 같은 그림 찾기.</strong><br>씨앗 단계는 정답 그림을 먼저 보여 줘요. 익숙해지면 새싹, 세 개를 고르고 싶으면 나무로 바꿔 주세요. 모를 땐 힌트를 쓰면 돼요.</span></li><li><span><strong>말하기는 하고 싶을 때만.</strong><br>“고양이가 왔네. Cat!”처럼 같이 반응해 주세요. 따라 말하지 않아도 괜찮아요. 발음 점수나 말하기 평가는 없어요.</span></li><li><span><strong>몸으로 한 번 더!</strong><br>Jump는 안전한 자리에서 폴짝, Clap은 손뼉, Wave는 손 흔들기예요. 앉아서 손으로만 표현해도 좋아요. 움직임을 줄이면 보호자가 먼저 보여 주세요.</span></li><li><span><strong>즐거울 때 짧게 마쳐요.</strong><br>한 판은 여섯 번이에요. 함께 말하고 움직이며 5분 안팎으로, 원하면 더 일찍 마쳐도 좋아요. 스티커를 받고 “Bye!” 하며 쉬어요. 다시 만나기는 선택이에요.</span></li></ol><hr class="divider"><p class="parent-copy"><strong>오늘 만날 수 있는 15개 영어</strong><br>동물: cat · dog · rabbit · duck<br>과일: apple · banana · pear · blueberry<br>색깔: red · yellow · green · blue<br>동작: jump · clap · wave</p><p class="parent-copy" style="margin-top:15px">과일은 이름을, 색 바구니는 색깔을 들어요. 두 놀이는 안내와 화면에서 구분해요. 소리가 없는 환경에서는 힌트 그림과 보호자 읽기로 도와주세요.</p></div>`;d.showModal();}
function openStickers(){stopAudio();const d=document.getElementById('stickers-dialog');d.innerHTML=`${dialogHead('나의 숲 스티커','stickers-title')}<div class="dialog-body"><p>함께 논 기억을 여기 모았어요.</p><div class="sticker-grid">${STICKERS.map((s,i)=>`<div class="sticker-slot ${saved.stickers.includes(i)?'':'empty'}" aria-label="${saved.stickers.includes(i)?['곰','꽃','나비','딸기','무지개','나무'][i]+' 스티커':'비어 있는 자리'}">${saved.stickers.includes(i)?s:'✧'}</div>`).join('')}</div><p class="parent-copy">다 모으지 않아도 괜찮아요. 언제든 쉬어도, 다시 놀아도 좋아요.</p></div>`;d.showModal();}
function dispatchAction(action){switch(action){case 'home':home();break;case 'sound':settings.sound=!settings.sound;stopAudio();audioState=settings.sound?'idle':'muted';persist();render();break;case 'settings':openSettings();break;case 'guide':openGuide();break;case 'stickers':openStickers();break;case 'welcome-audio':speak([{lang:'ko',text:'안녕! 곰 친구야. 토끼, 사과, 손 그림 중에 하고 싶은 놀이를 골라줘. 잘 들어보고 그림을 콕 눌러보자!'},{lang:'en',text:'Hello!'}]);break;case 'listen':prompt();break;case 'instruction':prompt(true);break;case 'retry-audio':settings.sound=true;persist();loadVoices();audioState='idle';render();if(screen==='play')prompt(true);else speak([{lang:'ko',text:'안녕! 곰 친구야.'},{lang:'en',text:'Hello!'}]);break;case 'hint':{const r=currentRound();r.hinted=true;if(!saved.missed.includes(r.target.id))saved.missed.push(r.target.id);if(!session.missed.includes(r.target.id))session.missed.push(r.target.id);persist();render();prompt();break;}case 'next':nextRound();break;case 'say-together':speak([{lang:'en',text:currentRound().target.en}]);break;case 'review-session':startGame('review',session.missed);break;case 'test-voice':settings.sound=true;persist();speak([{lang:'ko',text:'안녕! 곰 친구와 영어로 놀아볼까?'},{lang:'en',text:'Hello! Apple. Cat.'}]);{const status=document.getElementById('voice-status');if(status)status.textContent=!synth?'이 브라우저는 음성을 지원하지 않아요. 그림 힌트와 보호자 읽기를 사용해 주세요.':'영어와 한국어가 들리는지 확인해 주세요. 안 들리면 기기 음소거를 확인하거나 다른 목소리를 골라 주세요.';}break;case 'reset-ask':document.getElementById('reset-area').innerHTML='<div class="reset-confirm"><p>스티커, 다시 만날 낱말, 설정을 이 브라우저에서 모두 지울까요?</p><div class="buttons"><button class="danger-btn" data-action="reset-confirm">모두 초기화</button><button class="soft-btn" data-action="reset-cancel">취소</button></div></div>';break;case 'reset-cancel':document.getElementById('reset-area').innerHTML='';break;case 'reset-confirm':stopAudio();saved={settings:{...defaults},stickers:[],missed:[]};settings=saved.settings;persist();home();document.getElementById('parent-dialog').close();openSettings();document.getElementById('settings-status').textContent='기록과 설정을 초기화했어요.';break;}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-close')){b.closest('dialog').close();return;}if(b.dataset.start){startGame(b.dataset.start);return;}if(b.dataset.answer){choose(b.dataset.answer);return;}if(b.dataset.word){speak([{lang:'en',text:BY_ID[b.dataset.word].en}]);return;}if(b.dataset.level){settings.level=Number(b.dataset.level);persist();document.querySelectorAll('[data-level]').forEach(x=>{x.classList.toggle('active',Number(x.dataset.level)===settings.level);x.setAttribute('aria-pressed',String(Number(x.dataset.level)===settings.level));});return;}if(b.dataset.action)dispatchAction(b.dataset.action);});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.setting){settings[el.dataset.setting]=el.type==='checkbox'?el.checked:el.value;persist();if(el.dataset.setting==='sound'){stopAudio();audioState=settings.sound?'idle':'muted';}render();}if(el.dataset.voice){settings[el.dataset.voice+'Voice']=el.value;persist();}});
for(const d of document.querySelectorAll('dialog')){d.addEventListener('click',e=>{if(e.target===d){const rect=d.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)d.close();}});d.addEventListener('close',()=>{stopAudio();render();});}
window.addEventListener('pagehide',stopAudio);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAudio();});
if(synth){loadVoices();synth.addEventListener?.('voiceschanged',loadVoices);}
applyMotion();render();
function stateSnapshot(){return {screen,game:session?.game||null,level:session?.level||settings.level,round:session?session.index+1:null,totalRounds:session?.rounds.length||0,completed:session?.finished||false,sound:settings.sound,voiceAvailable:voices.some(v=>v.lang.toLowerCase().startsWith('en')),stickers:saved.stickers.length,missedWords:[...saved.missed],choices:screen==='play'?currentRound().choices.map(w=>({id:w.id,label:w.ko})):[],target:screen==='play'?currentRound().target.id:null,answered:screen==='play'?currentRound().correct:false};}
const modelContext=document.modelContext;if(modelContext?.registerTool){const lifecycle=new AbortController();const tools=[{name:'read_english_game_state',title:'Read English game state',description:'Read the currently visible game, choices and device-local settings. Does not play audio or change the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('No input properties are accepted.');return stateSnapshot();}},{name:'start_english_game',title:'Start English picture game',description:'Start a new six-round game in the visible interface. This replaces an unfinished round. Audio may require the person to press the visible speaker button.',inputSchema:{type:'object',properties:{game:{type:'string',enum:['animals','picnic','actions']}},required:['game'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='game')||!['animals','picnic','actions'].includes(input.game))throw new Error('Choose animals, picnic, or actions.');startGame(input.game);return {...stateSnapshot(),audioMayNeedUserGesture:true};}}];for(const tool of tools){try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(e){}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
